### ISSUE TITLE
Permanent crash after adding image to KolabNotes

### ISSUE THREAD

**Issue by eliasp** [konradrenner/kolabnotes-android#160]
KolabNotes crashed here when trying to add a photo to KolabNotes using the "Share" functionality of the photo app.

Since then KolabNotes can't be started anymore and crashes immediately on startup without even showing the UI.

**Device:** OnePlus 3
**OS:** Android 7.1.1
**App Version:** 2.6.0

Crash Log:
```
04-09 22:36:45.045 32297 32297 E AndroidRuntime: FATAL EXCEPTION: main
04-09 22:36:45.045 32297 32297 E AndroidRuntime: Process: org.kore.kolabnotes.android, PID: 32297
04-09 22:36:45.045 32297 32297 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kore.kolabnotes.android/org.kore.kolabnotes.android.MainActivity}: java.lang.IllegalStateException: Couldn't read row 0, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2728)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6290)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.database.CursorWindow.nativeGetString(Native Method)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.database.CursorWindow.getString(CursorWindow.java:438)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at org.kore.kolabnotes.android.content.NoteRepository.cursorToNoteWithoutDescription(NoteRepository.java:355)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at org.kore.kolabnotes.android.content.NoteRepository.getAll(NoteRepository.java:241)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at org.kore.kolabnotes.android.fragment.OverviewFragment$DrawerItemClickedListener.changeNoteSelection(OverviewFragment.java:1573)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at org.kore.kolabnotes.android.fragment.OverviewFragment$DrawerItemClickedListener.onItemClick(OverviewFragment.java:1533)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at com.mikepenz.materialdrawer.DrawerUtils.setListSelection(DrawerUtils.java:107)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at com.mikepenz.materialdrawer.Drawer.setSelection(Drawer.java:411)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at com.mikepenz.materialdrawer.Drawer.setSelection(Drawer.java:398)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at org.kore.kolabnotes.android.fragment.OverviewFragment.onActivityCreated(OverviewFragment.java:269)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.Fragment.performActivityCreated(Fragment.java:2362)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2039)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:176)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.Activity.performCreateCommon(Activity.java:6754)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6762)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
04-09 22:36:45.045 32297 32297 E AndroidRuntime: 	... 9 more
04-09 22:36:45.045 32297 32297 D AppTracker: App Event: crash
```

Do you need any further data to debug this issue?

**Comment by konradrenner** [comment]
Hi, 
thanks for reporting! I was able to reproduce it, will have a look on it.

**Comment by konradrenner** [comment]
problem is the size of the image. android sqllite cursor is limited to 1 MB when reading a row. So I will have to show a message that images can't be inlined if the are at least 1 MB.  @eliasp did you enable "show note preview" ?

**Comment by konradrenner** [comment]
I will do a fix tonight. The fix will be that in the note overview the description column is not read, if the "show note preview" is disabled, so the app will start again and it is possible to delete the note with the images which is too big. There will also be a check if one wants to insert a image into a note which is bigger than 900 kB. If one wants to add a bigger images, this must be done via the attachment functionality

**Comment by eliasp** [comment]
> @eliasp did you enable "show note preview" ?

I can't tell - it's not my phone but a family member's one.

**Comment by konradrenner** [comment]
@eliasp should be fixed with the latest version (committed this moment :-) ). please let me know if it is possible for your family member to open the app.

**Comment by eliasp** [comment]
@konradrenner thanks a lot - the problem is fixed. It crashed when trying to open the note which initially caused this issue, but I was able to justs delete it now.

**Comment by konradrenner** [comment]
Great to hear!
