### ISSUE TITLE
App crashes on clicking hamburger icon immediately after creating a new note

### ISSUE THREAD

**Issue by neupanedipen** [konradrenner/kolabnotes-android#184]
#### Expected behaviour 
The app must be stable on trying to access other menus immediately after creating a new notebook.
#### Actual behaviour 
But the app crashes on clicking the three horizontal lines immediately after creating a new notebook.
#### How to reproduce 
1. Install the app from fdroid and launch it.
2. Click on pencil icon and create a new note with any name.
3. Now click on three vertical dots from top right corner of the app and click on "New Notebook" option and create a new notebook with any name.
4. Now after creating the notebook click on three horizontal lines from top left corner of the app. 
The app crashes.
* App version: 3.1.3
* Device: Samsung Galaxy Tab 3
* Operating system: Android 4.4.2
#### Recording of the bug
https://youtu.be/tfKq4Xb7XWQ
##### logcat
```
FATAL EXCEPTION: main
Process: org.kore.kolabnotes.android, PID: 26606
java.lang.NullPointerException
	at org.kore.kolabnotes.android.fragment.DetailFragment.onBackPressed(DetailFragment.java:1495)
	at org.kore.kolabnotes.android.fragment.DetailFragment$1.onClick(DetailFragment.java:200)
	at android.view.View.performClick(View.java:4633)
	at android.view.View$PerformClick.run(View.java:19280)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5598)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by konradrenner** [comment]
Thank you for the detailed infromations about the problem!

**Comment by konradrenner** [comment]
should be fixed with latest release
