### ISSUE TITLE
Apps crashes when rotate device

### ISSUE THREAD

**Issue by geniuslittleteddy** [konradrenner/kolabnotes-android#207]
Apps crashes when I rotate my device on the following page (It crashes especially when I add two drawers in the webview)

![Screen Shot 2020-07-02 at 10 43 19 PM](https://user-images.githubusercontent.com/67744580/86373024-82ee9e00-bcb5-11ea-8c2c-3bca7882c9d7.png)

![Screen Shot 2020-07-02 at 10 33 28 PM](https://user-images.githubusercontent.com/67744580/86372695-1ecbda00-bcb5-11ea-9051-8e2059398274.png)

```
07-02 22:39:46.250  3789  3789 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kore.kolabnotes.android/org.kore.kolabnotes.android.DetailActivity}: java.lang.StringIndexOutOfBoundsException: length=9834; regionStart=9834; regionLength=3
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4483)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(ActivityThread.java)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: Caused by: java.lang.StringIndexOutOfBoundsException: length=9834; regionStart=9834; regionLength=3
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at java.lang.String.substring(String.java:1931)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at org.kore.kolabnotes.android.fragment.DetailFragment.initImageMap(DetailFragment.java:1368)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at org.kore.kolabnotes.android.fragment.DetailFragment.onActivityCreated(DetailFragment.java:260)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.Fragment.performActivityCreated(Fragment.java:2361)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2039)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:176)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.Activity.performCreateCommon(Activity.java:6658)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6666)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
07-02 22:39:46.250  3789  3789 E AndroidRuntime: 	... 10 more
07-02 22:39:46.255  1488  1510 W ActivityManager:   Force finishing activity org.kore.kolabnotes.android/.DetailActivity
```

**Comment by konradrenner** [comment]
is it reproduceable every time, or are there some requirements that it happens?

**Comment by geniuslittleteddy** [comment]
Hi, it is reproduceable every time
