### ISSUE TITLE
App crashes when rotating devices

### ISSUE THREAD

**Issue by geniuslittleteddy** [konradrenner/kolabnotes-android#208]
This one is the same with #207 but has a different exception log.

```
06-24 14:28:38.590  2546  2546 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:828)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at java.lang.StringBuilder.replace(StringBuilder.java:267)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at org.kore.kolabnotes.android.fragment.DetailFragment.repairImages(DetailFragment.java)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at org.kore.kolabnotes.android.fragment.DetailFragment.onSaveInstanceState(DetailFragment.java)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.Fragment.performSaveInstanceState(Fragment.java:2514)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1763)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1820)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.FragmentController.saveAllState(FragmentController.java:112)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.Activity.onSaveInstanceState(Activity.java:1485)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at androidx.core.app.ComponentActivity.onSaveInstanceState(ComponentActivity.java)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at org.kore.kolabnotes.android.DetailActivity.onSaveInstanceState(DetailActivity.java)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.Activity.performSaveInstanceState(Activity.java:1414)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1300)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4505)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4456)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(ActivityThread.java)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
06-24 14:28:38.590  2546  2546 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
06-24 14:28:38.597  1611  1667 W ActivityManager:   Force finishing activity org.kore.kolabnotes.android/.DetailActivity
```

**Comment by konradrenner** [comment]
is it reproduceable every time, or are there some requirements that it happens?

**Comment by geniuslittleteddy** [comment]
Hi, it is reproduceable every time
