### ISSUE TITLE
App crashes when rotating devices

### ISSUE THREAD

**Issue by geniuslittleteddy** [konradrenner/kolabnotes-android#209]
Also another one same with #208 #207 but has a different exception log.

```
06-24 14:46:42.341 10898 10898 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
06-24 14:46:42.341 10898 10898 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:828)
06-24 14:46:42.341 10898 10898 E AndroidRuntime: 	at java.lang.StringBuilder.replace(StringBuilder.java:267)
06-24 14:46:42.341 10898 10898 E AndroidRuntime: 	at org.kore.kolabnotes.android.fragment.DetailFragment.repairImages(DetailFragment.java)
06-24 14:46:42.341 10898 10898 E AndroidRuntime: 	at org.kore.kolabnotes.android.fragment.DetailFragment.saveNote(DetailFragment.java)
06-24 14:46:42.341 10898 10898 E AndroidRuntime: 	at org.kore.kolabnotes.android.fragment.DetailFragment.save(DetailFragment.java)
06-24 14:46:42.341 10898 10898 E AndroidRuntime: 	at org.kore.kolabnotes.android.DetailActivity.onPause(DetailActivity.java)
06-24 14:46:42.341 10898 10898 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:6804)
06-24 14:46:42.341 10898 10898 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
06-24 14:46:42.341 10898 10898 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3711)
06-24 14:46:42.341 10898 10898 E AndroidRuntime: 	... 11 more
```

**Comment by konradrenner** [comment]
is it reproduceable every time, or are there some requirements that it happens?

**Comment by geniuslittleteddy** [comment]
Hi, it is reproduceable every time
