### ISSUE TITLE
App crashes when typing "%"

### ISSUE THREAD

**Issue by SmallJoker** [konradrenner/kolabnotes-android#222]
Affects version: 5.0.1
Installed from F-Droid

When typing `%` into the notes area, the following error appears.

```
 I  nativeRelease nativeObject s[523503872736]
 I  nativeRelease nativeObject e[523503872736]
[DetailActivity]  I  Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=8 res=0x1 s={true 523519963136} ch=false fn=27
 I  [DP] pd() Asnyc report
libEGL  W  EGLNativeWindowType 0x79e438b010 disconnect failed
[DetailActivity]  I  [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$performDraw$1$ViewRootImpl:4668 android.view.-$$Lambda$ViewRootImpl$DJd0VUYJgsebcnSohO6h8zc_ONI.run:6 android.os.Handler.handleCallback:938
 I  [DP] rdf()
cr_AwAutofillManager  W  Autofill is disabled: AutofillManager isn't available in given Context."
AndroidRuntime m D  Shutting down VM
 E  FATAL EXCEPTION: main
 E  Process: org.kore.kolabnotes.android, PID: 23256
 E  java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
 E      at java.net.URLDecoder.decode(URLDecoder.java:196)
 E      at jp.wasabeef.richeditor.RichEditor$EditorWebViewClient.shouldOverrideUrlLoading(RichEditor.java:425)
 E      at org.kore.kolabnotes.android.fragment.KolabNotesRichEditor$KolabNotesEditorWebViewClient.shouldOverrideUrlLoading(KolabNotesRichEditor.java:48)
 E      at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
 E      at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.aab-stable-666810033:124)
 E      at android.os.MessageQueue.nativePollOnce(Native Method)
 E      at android.os.MessageQueue.next(MessageQueue.java:335)
 E      at android.os.Looper.loop(Looper.java:206)
 E      at android.app.ActivityThread.main(ActivityThread.java:8653)
 E      at java.lang.reflect.Method.invoke(Native Method)
 E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
 E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Process  I  Sending signal. PID: 23256 SIG: 9
```

Post-processed output from https://github.com/JakeWharton/pidcat/blob/master/pidcat.py

`python pidcat.py org.kore.kolabnotes.android`

**Comment by SmallJoker** [comment]
Workaround: Disable the rich text editor mode in the settings.

**Comment by konradrenner** [comment]
Hi, thank you for using the app. This is a known  bug in the rich text library which is used. I will leave the issue open, so that other users can read about the workaround.
