### ISSUE TITLE
NullPointer at onResume in MainActivity

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#31]
This NullPointer sometimes occurs when saving a note, when the app wants to go back to the MainActivity:

java.lang.RuntimeException: Unable to resume activity {org.kore.kolabnotes.android/org.kore.kolabnotes.android.MainPhoneActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.kore.kolab.notes.Identification org.kore.kolab.notes.Notebook.getIdentification()' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.kore.kolab.notes.Identification org.kore.kolab.notes.Notebook.getIdentification()' on a null object reference
at org.kore.kolabnotes.android.MainPhoneActivity.onResume(MainPhoneActivity.java:273)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
at android.app.Activity.performResume(Activity.java:6076)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
... 9 more

**Comment by konradrenner** [comment]
solved
