### ISSUE TITLE
NullPointer at onCreate in DetailActivity

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#34]
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kore.kolabnotes.android/org.kore.kolabnotes.android.DetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.kore.kolab.notes.Note.getSummary()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.kore.kolab.notes.Note.getSummary()' on a null object reference
at org.kore.kolabnotes.android.DetailActivity.onCreate(DetailActivity.java:132)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
... 10 more

**Comment by konradrenner** [comment]
solved
