### ISSUE TITLE
Unable to start DetailActivity

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#37]
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kore.kolabnotes.android/org.kore.kolabnotes.android.DetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.kore.kolab.notes.Notebook.getSummary()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at

**Comment by konradrenner** [comment]
will be solved with next alpha version
