### ISSUE TITLE
Exception in checkModificationPermissions(Notebook)

### ISSUE THREAD

**Issue by proninyaroslav** [konradrenner/kolabnotes-android#94]
Hello. If you try to move (when editing notes, not during creation) note to another notebook (not shared notebook), occurs exception:

```
FATAL EXCEPTION: main
Process: org.kore.kolabnotes.android, PID: 31203
java.lang.ClassCastException: org.kore.kolab.notes.Notebook cannot be cast to org.kore.kolab.notes.SharedNotebook
at org.kore.kolabnotes.android.fragment.DetailFragment.checkModificationPermissions(DetailFragment.java:1100)
at org.kore.kolabnotes.android.fragment.DetailFragment.saveNote(DetailFragment.java:1052)
at org.kore.kolabnotes.android.fragment.DetailFragment.onOptionsItemSelected(DetailFragment.java:724)
at android.app.Fragment.performOptionsItemSelected(Fragment.java:2326)
at android.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2072)
at android.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:290)
at android.app.Activity.onMenuItemSelected(Activity.java:2917)
at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:73)
at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
at android.view.View.performClick(View.java:5204)
at android.view.View$PerformClick.run(View.java:21156)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5466)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by konradrenner** [comment]
Thx will first merge your pull request, then fix this.

**Comment by konradrenner** [comment]
fixed in next version
