### ISSUE TITLE
Exception in checkDifferences

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#96]
java.lang.NullPointerException
    at org.kore.kolabnotes.android.fragment.DetailFragment.checkDifferences(DetailFragment.java:1287)
    at org.kore.kolabnotes.android.fragment.OverviewFragment.onSelect(OverviewFragment.java:321)
    at org.kore.kolabnotes.android.adapter.NoteAdapter$ClickListener.onClick(NoteAdapter.java:228)
    at android.view.View.performClick(View.java:4640)
    at android.view.View$PerformClick.run(View.java:19431)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5598)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by konradrenner** [comment]
fixed with next version
